#!/bin/ksh

# configuration file for timeseries script
# add here machine dependent set up
# It expects USER* variables defined in conf_users.sh

# --- TOOLS -----
# Required programs, including compression options
module unload cdo hdf5 netcdf python numpy
module load hdf5/1.8.17--intel--pe-xe-2017--binary netcdf/4.4.1--intel--pe-xe-2017--binary cdo python/2.7.12 numpy/1.11.2--python--2.7.12

export ${USERexp:=$USER}
export ECE3_POSTPROC_DIAGDIR='$HOME/ecearth3/diag'

# *** POST_DIR: where to store post-processed EC-Earth files generated by XXXX
#               With <RUN> replacing the name of your experiment:
#export POST_DIR="/nobackup/vagn2/john/tmp/post/<RUN>"
export ECE3_POSTPROC_POSTDIR="/marconi_scratch/userexternal/${USER}/ece3/${EXPID}/post"

export MESHDIR_TOP="/marconi_work/Pra13_3311/ecearth3/nemo"


# About web page, on remote server host:
#     =>  set RHOST="" to disable this function...
export RHOST=""
export RUSER=""
export WWW_DIR_ROOT=""
#export RHOST="misu228.misu.su.se"
#export RUSER0="laurent"
#export WWW_DIR_ROOT="/data/www/ecev3"


############################
# About required software   #
############################

# support for GRIB_API?
# Set the directory where the GRIB_API tools are installed
# Note: cdo had to be compiled with GRIB_API support for this to work
# This is only required if your highest level is above 1 hPa,
# otherwise leave GRIB_API_BIN empty (or just comment the line)!
#export GRIB_API_BIN="/home/john/bin"

# The CDFTOOLS set of executables should be found into:
export CDFTOOLS_BIN="$WORK/opt/bin"

# The scrip "rebuild" as provided with NEMO (relies on flio_rbld.exe):
export RBLD_NEMO="$WORK/ecearth3/rebuild_nemo/rebuild_nemo"

#python
export PYTHON="python"

# job scheduler submit command
submit_cmd="sbatch"


